--- 
# config file for curator stats
# paths to important directories
base_dir: "./"

# directory suffixes for concatenation
concat_dirs:
  filled_templates: "templates/filled/"
  fetch_data: "fetch_data/"


# length of header to be ignored
header_len: 7

# example config option
sample_types:
- "Animal"
- "Human"
- "Environmental"
- "Ocean"
...